site_name: Taller de Git
site_author: "Oscar Abuawad <oscarabuawad@hotmail.com>"
site_description: "Curso básico de git"
site_url: "https://github.com/n00bDr01d/taller-git.git"

repo_name: "n00bDr01d/taller-git"
repo_url: "https://github.com/n00bDr01d/taller-git.git"

copyright: Copyleft - CC BY-NC 4.0 - Aula de Software Libre

theme:
  favicon: "images/logoasl.png"
  features:
    - navigation.instant
  icon:
    logo: material/git
  name: "material"
  language: "es"
  palette:
    - scheme: slate
      accent: indigo

plugins:
  - awesome-pages
  - git-revision-date-localized:
      type: date
  - search

extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: ""
    - icon: fontawesome/brands/twitter
      link: ""
    - icon: fontawesome/brands/facebook
      link: ""
    - icon: fontawesome/brands/instagram
      link: ""
    - icon: fontawesome/brands/youtube
      link: ""

markdown_extensions:
  - admonition: ~
  - attr_list: ~
  - def_list: ~
  - footnotes: ~
  - toc:
      permalink: true
  - pymdownx.keys: ~
  - pymdownx.highlight: ~
  - pymdownx.inlinehilite: ~
  - pymdownx.superfences: ~

google_analytics:
  - ""
  - ""
